version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.1.4
    - 2.2.1
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
  - dependency-name: svelte
    versions:
    - 3.36.0
