name: Check, Build & Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '12.20'

      - name: Install Dependencies
        run: yarn

      - name: Svelte Check
        run: yarn run check

      - name: Build
        run: yarn run build:deploy

      # - name: Deploy
      #   uses: dswistowski/surge-sh-action@v1
      #   with:
      #     domain: 'https://donnisnoni-form-builder.surge.sh'
      #     project: './dist'
      #     login: ${{ secrets.surge_login }}
      #     token: ${{ secrets.surge_token }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
